recorded_data:
  # Bag files to plot cubic Hermite interpolation data below
  # bag_names: [TODO]
  # topic_names: [/mpc/rec/interp_data]

  # Bag files to determine model mismatch below
  bag_names:
    [
      traj_circle_r1_f0dot3_cw,
      traj_circle_r1_f0dot3_ccw,
      traj_lemniscate_r1_f0dot3_cw,
      traj_lemniscate_r1_f0dot3_ccw,
    ]
  topic_names: [/step_control, /falcon/odometry, /w, /eta]

  # Bag files to calibrate tightening below
  # bag_names: [TODO]
  # topic_names:
  #   [
  #     /falcon/ground_truth/odometry,
  #     /mpc/rec/current_state,
  #     /mpc/rec/nominal_reference,
  #     /mpc/rec/predicted_trajectory/0,
  #   ]

  # Bag files to evaluate ROHMPC scheme below
  # bag_names: [TODO]
  # topic_names:
  #   [
  #     /falcon/ground_truth/odometry,
  #     /grid/obs/rec/rectangle2x1_0,
  #     /grid/obs/rec/rectangle2x1_1,
  #     /mpc/rec/current_state,
  #     /mpc/rec/predicted_trajectory/0,
  #     /mpc/rec/predicted_trajectory/1,
  #     /mpc/rec/reference_trajectory/0,
  #   ]
  time_precision: 5

supported_topic_names:
  [
    /eta,
    /falcon/ground_truth/odometry,
    /falcon/odometry,
    /grid/obs/rec/rectangle2x1_0,
    /grid/obs/rec/rectangle2x1_1,
    /mpc/rec/current_state,
    /mpc/rec/interp_data,
    /mpc/rec/nominal_reference,
    /mpc/rec/predicted_trajectory/0,
    /mpc/rec/predicted_trajectory/1,
    /mpc/rec/reference_trajectory/0,
    /step_control,
    /w,
  ]
