recorded_data:
  bag_dir: /media/storage/Downloads/agisim/bags
  # bag_names:
  #   [
  #     2025-07-03_gaz_falcon_mpc_model_id_inertia_matrix_dist_no_meas_noise_only_thrust_dragtorque,
  #   ]
  # topic_names: [/step_control, /falcon/odometry]
  # bag_names:
  #   [
  #     2025-06-27_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_gaz_dist_meas_noise,
  #   ]
  # bag_names:
  #   [
  #     2025-07-07_gaz_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_dist_meas_noise,
  #     2025-07-07_gaz_falcon_mpc_model_mismatch_circle_r1_f0dot1_ccw_dist_meas_noise,
  #     2025-07-08_gaz_falcon_mpc_model_mismatch_lemniscate_r1_f0dot1_cw_dist_meas_noise,
  #     2025-07-08_gaz_falcon_mpc_model_mismatch_lemniscate_r1_f0dot1_ccw_dist_meas_noise,
  #   ]
  # bag_names:
  #   [
  #     2025-07-09_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_no_dist_no_meas_noise,
  #     2025-07-09_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_dist_meas_noise,
  #   ]
  # bag_names:
  #   [
  #     2025-07-14_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_no_dist_no_meas_noise,
  #   ]
  # bag_names:
  #   [
  #     2025-07-15_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_no_dist_no_meas_noise,
  #     2025-07-15_sim_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_dist_meas_noise,
  #   ]
  # bag_names:
  #   [
  #     2025-07-15_gaz_falcon_mpc_model_mismatch_circle_r1_f0dot1_cw_dist_meas_noise,
  #     2025-07-15_gaz_falcon_mpc_model_mismatch_circle_r1_f0dot1_ccw_dist_meas_noise,
  #     2025-07-15_gaz_falcon_mpc_model_mismatch_lemniscate_r1_f0dot1_cw_dist_meas_noise,
  #     2025-07-15_gaz_falcon_mpc_model_mismatch_lemniscate_r1_f0dot1_ccw_dist_meas_noise,
  #   ]
  # topic_names: [/step_control, /falcon/odometry, /w, /eta]
  # bag_names:
  #   [
  #     2025-07-15_sim_falcon_cubic_hermite_interpolation,
  #     2025-07-15_sim_falcon_cubic_hermite_interpolation_2nd_input,
  #   ]
  bag_names: [2025-07-19_sim_falcon_cubic_hermite_interpolation]
  topic_names: [/mpc/rec/interp_data]
  # bag_names: [2025-07-16_sim_falcon_hmpc_no_P_no_dist_K_no_meas_noise_L]
  # bag_names: [2025-07-16_sim_falcon_hmpc_no_dist_K_no_meas_noise_L]
  # bag_names: [2025-07-17_sim_falcon_hmpc_no_dist_K_no_meas_noise_L]
  # bag_names: [2025-07-17_sim_falcon_hmpc_Qpos10_no_dist_K_no_meas_noise_L]
  # bag_names:
  #   [2025-07-17_sim_falcon_hmpc_Q1000eye_R1000eye_no_dist_K_no_meas_noise_L]
  # bag_names: [2025-07-18_sim_falcon_hmpc_R1000eye_no_dist_K_no_meas_noise_L]
  # topic_names:
  #   [
  #     /falcon/ground_truth/odometry,
  #     /mpc/rec/current_state,
  #     /mpc/rec/reference_trajectory/0,
  #     /mpc/rec/predicted_trajectory/0,
  #   ]
  time_precision: 5

supported_topic_names:
  [
    /step_control,
    /falcon/ground_truth/odometry,
    /falcon/odometry,
    /w,
    /eta,
    /mpc/rec/current_state,
    /mpc/rec/interp_data,
    /mpc/rec/reference_trajectory/0,
    /mpc/rec/predicted_trajectory/0,
  ]
